/**
 * Offline verification of the native-app (MOBILE_APP) Snap Purchase.
 *   npx tsx scripts/verify-snap-app.ts [report.md]
 * Runs the real builder, device-context parser, ledger and HTTP sender against
 * an in-memory DB and a fake Snap endpoint. Exits non-zero on failure.
 */
import crypto from 'crypto';
import fs from 'fs';

const ENV = {
  SNAP_CAPI_ACCESS_TOKEN: 'test-token',
  SNAP_APP_ID_IOS: 'snap-app-ios-uuid',
  SNAP_APP_ID_ANDROID: 'snap-app-android-uuid',
  SNAP_IOS_APP_STORE_ID: '6740012345',
  SNAP_ANDROID_PACKAGE: 'com.zicabella.app',
  NEXT_PUBLIC_SITE_URL: 'https://zicabella.com',
} as Record<string, string>;
Object.assign(process.env, ENV);

let failed = 0, passed = 0;
const check = (l: string, ok: boolean, d?: unknown) => { if (ok) passed++; else failed++; console.log(`${ok ? 'PASS' : 'FAIL'}  ${l}${ok || d === undefined ? '' : `\n      ${JSON.stringify(d)}`}`); };
const eq = (l: string, got: unknown, want: unknown) => check(l, JSON.stringify(got) === JSON.stringify(want), { got, want });
const h = (v: string) => crypto.createHash('sha256').update(v).digest('hex');
const report: string[] = ['# Snap MOBILE_APP Purchase — verified payloads', '', `Generated by scripts/verify-snap-app.ts on ${new Date().toISOString()}`, ''];

const httpCalls: Array<{ url: string; body: any }> = [];
(globalThis as any).fetch = async (url: string, opt: any = {}) => {
  httpCalls.push({ url: String(url), body: opt.body ? JSON.parse(opt.body) : undefined });
  return { ok: true, status: 200, json: async () => ({ status: 'VALID' }) };
};

async function main() {
  const appCapi = await import('../lib/snap/app-capi');
  const { createSnapAppPurchaseDelivery } = await import('../lib/snap/app-purchase');

  // ── in-memory DB ──
  const orders = new Map<string, any>();
  const rows = new Map<string, any>();
  const keyOf = (w: any) => { const k = w.platform_eventName_orderId; return `${k.platform}|${k.eventName}|${k.orderId}`; };
  const tick = () => new Promise(r => setImmediate(r));
  const match = (row: any, w: any): boolean => {
    if (w.id && row.id !== w.id) return false;
    if (w.platform && row.platform !== w.platform) return false;
    if (w.eventName && row.eventName !== w.eventName) return false;
    if (w.attempts?.lt !== undefined && !(row.attempts < w.attempts.lt)) return false;
    if (w.status !== undefined) { if (typeof w.status === 'string' && row.status !== w.status) return false; if (w.status?.in && !w.status.in.includes(row.status)) return false; }
    if (w.leaseUntil?.lt && !(row.leaseUntil && row.leaseUntil < w.leaseUntil.lt)) return false;
    if (w.OR && !w.OR.some((o: any) => match(row, o))) return false;
    return true;
  };
  let seq = 0;
  const db = {
    order: { findUnique: async ({ where }: any) => { await tick(); return orders.get(where.id) || null; } },
    adConversionDelivery: {
      findUnique: async ({ where }: any) => { await tick(); const r = rows.get(keyOf(where)); return r ? { ...r } : null; },
      create: async ({ data }: any) => { await tick(); const k = `${data.platform}|${data.eventName}|${data.orderId}`;
        if (rows.has(k)) { const e: any = new Error('dup'); e.code = 'P2002'; throw e; }
        const r = { id: `r${++seq}`, status: 'pending', attempts: 0, leaseUntil: null, eventTime: null, sentAt: null, createdAt: new Date(), updatedAt: new Date(), ...data };
        rows.set(k, r); return { ...r }; },
      update: async ({ where, data }: any) => { await tick(); const r = rows.get(keyOf(where)); Object.assign(r, data); return { ...r }; },
      updateMany: async ({ where, data }: any) => { await tick(); let count = 0;
        for (const r of rows.values()) { if (!match(r, where)) continue; for (const [k, v] of Object.entries<any>(data)) r[k] = v && typeof v === 'object' && 'increment' in v ? r[k] + v.increment : v; count++; }
        return { count }; },
      findMany: async ({ where, take }: any) => [...rows.values()].filter(r => match(r, where)).slice(0, take),
    },
  };
  const delivery = createSnapAppPurchaseDelivery({ db, send: appCapi.sendSnapAppEvent, env: ENV as any });
  const PAID = { paymentConfirmed: true };
  const req = { ipAddress: '49.36.10.20', userAgent: 'ZicaBella/8 CFNetwork/1494 Darwin/23.5.0', externalId: 'cust_app_1' };

  const order = (id: string, over: any = {}) => ({
    id, orderType: 'MOBILE_APP', paymentStatus: 'paid', totalPrice: 3797, currency: 'INR', customerId: 'cust_app_1',
    createdAt: new Date(Date.now() - 90e3), paymentCapturedAt: new Date(Date.now() - 60e3),
    customer: { email: 'Aarav@Example.com', phone: '9876543210', name: 'Aarav Mehta' },
    shippingAddress: JSON.stringify({ city: 'Noida', province: 'Uttar Pradesh', zip: '201304', country: 'India' }),
    items: [{ variantId: '51813148262681', sku: 'ZB-AERO-XS', quantity: 2, price: 1499 },
            { variantId: '51813148328217', sku: 'ZB-TEE-M', quantity: 1, price: 799 }],
    ...over,
  });
  const iosDevice = {
    platform: 'ios', appPackage: 'com.zicabella.ios', appVersion: '1.0.2', buildNumber: '9', osVersion: '17.5.1',
    deviceModel: 'iPhone15,2', locale: 'en_IN', timezoneAbbr: 'GMT+5:30', timezone: 'Asia/Kolkata',
    screenWidth: 1179, screenHeight: 2556, screenDensity: 3, attStatus: 'authorized',
    idfv: '3F2504E0-4F89-11D3-9A0C-0305E82C3301', madid: 'E9228286-4C4E-4789-9D95-15827DCB291B',
  };
  const androidDevice = {
    platform: 'android', appPackage: 'com.zicabella.app', appVersion: '1.0.4', buildNumber: '5', osVersion: '14',
    deviceModel: 'SM-S918B', locale: 'en_IN', timezoneAbbr: 'GMT+5:30', timezone: 'Asia/Kolkata',
    screenWidth: 1080, screenHeight: 2340, screenDensity: 2.625, madid: '38400000-8cf0-11bd-b23e-10b96e40000d',
  };
  const lastEvent = () => httpCalls[httpCalls.length - 1];

  // ── iOS, ATT authorized ──
  console.log('\n— iOS');
  orders.set('app_ios_1', order('app_ios_1'));
  await delivery.recordSnapAppContext('app_ios_1', iosDevice, req); // at create-order
  httpCalls.length = 0;
  const res = await Promise.all([1, 2, 3, 4, 5].map(() => delivery.emitSnapAppPurchase('app_ios_1', PAID)));
  check('5 concurrent emits (verify + webhooks) → ONE send', httpCalls.length === 1, { calls: httpCalls.length, res });
  let call = lastEvent();
  check('sent to the iOS Snap APP endpoint (not the web pixel)', call.url.startsWith('https://tr.snapchat.com/v3/snap-app-ios-uuid/events?'), call.url);
  let ev = call.body.data[0];
  report.push('## iOS prepaid Purchase (ATT authorized)', '```json', JSON.stringify(ev, null, 2), '```', '');
  eq('action_source MOBILE_APP', ev.action_source, 'MOBILE_APP');
  eq('app_data.app_id = numeric App Store id', ev.app_data.app_id, '6740012345');
  eq('extinfo[0] = i2', ev.app_data.extinfo[0], 'i2');
  eq('extinfo[4] = OS version', ev.app_data.extinfo[4], '17.5.1');
  eq('extinfo has 16 slots', ev.app_data.extinfo.length, 16);
  eq('advertiser_tracking_enabled = 1 (ATT authorized)', ev.app_data.advertiser_tracking_enabled, 1);
  eq('idfv plain', ev.user_data.idfv, '3F2504E0-4F89-11D3-9A0C-0305E82C3301');
  eq('madid = IDFA lowercase, plain', ev.user_data.madid, 'e9228286-4c4e-4789-9d95-15827dcb291b');
  eq('ph hashed (India)', ev.user_data.ph, [h('919876543210')]);
  eq('em hashed', ev.user_data.em, [h('aarav@example.com')]);
  eq('external_id hashed', ev.user_data.external_id, [h('cust_app_1')]);
  eq('event_id = order_id = order id', [ev.event_id, ev.custom_data.order_id], ['app_ios_1', 'app_ios_1']);
  eq('value / currency from DB', [ev.custom_data.value, ev.custom_data.currency], [3797, 'INR']);
  eq('content_ids = feed.xml variant ids', ev.custom_data.content_ids, ['51813148262681', '51813148328217']);
  eq('num_items = 3', ev.custom_data.num_items, '3');
  check('no pixel_id / event_source_url', !('pixel_id' in ev) && !('event_source_url' in ev));
  httpCalls.length = 0;
  await delivery.emitSnapAppPurchase('app_ios_1', PAID);
  check('re-emit after success → no resend', httpCalls.length === 0);

  // ── iOS, ATT denied (and zero IDFA) ──
  orders.set('app_ios_2', order('app_ios_2'));
  await delivery.recordSnapAppContext('app_ios_2', { ...iosDevice, attStatus: 'denied', madid: '00000000-0000-0000-0000-000000000000' }, req);
  await delivery.emitSnapAppPurchase('app_ios_2', PAID);
  ev = lastEvent().body.data[0];
  report.push('## iOS prepaid Purchase (ATT denied)', '```json', JSON.stringify(ev, null, 2), '```', '');
  eq('ATT denied → advertiser_tracking_enabled = 0', ev.app_data.advertiser_tracking_enabled, 0);
  check('ATT denied → zero IDFA never sent', !('madid' in ev.user_data), ev.user_data);
  check('ATT denied → IDFV still sent (vendor id, not ATT-gated)', ev.user_data.idfv === iosDevice.idfv);

  // ── iOS COD upfront ──
  orders.set('app_ios_cod', order('app_ios_cod', { paymentStatus: 'cod_upfront_paid', paymentMethod: 'COD', totalPrice: 2499 }));
  await delivery.recordSnapAppContext('app_ios_cod', iosDevice, req);
  httpCalls.length = 0;
  await delivery.emitSnapAppPurchase('app_ios_cod', PAID);
  check('iOS COD (cod_upfront_paid) → one Purchase at full order value', httpCalls.length === 1 && lastEvent().body.data[0].custom_data.value === 2499);

  // ── Android ──
  console.log('\n— Android');
  orders.set('app_and_1', order('app_and_1'));
  await delivery.recordSnapAppContext('app_and_1', androidDevice, { ...req, userAgent: 'okhttp/4.12.0' });
  httpCalls.length = 0;
  await delivery.emitSnapAppPurchase('app_and_1', PAID);
  call = lastEvent();
  check('sent to the Android Snap APP endpoint', call.url.startsWith('https://tr.snapchat.com/v3/snap-app-android-uuid/events?'), call.url);
  ev = call.body.data[0];
  report.push('## Android prepaid Purchase (AAID available)', '```json', JSON.stringify(ev, null, 2), '```', '');
  eq('app_data.app_id = package name', ev.app_data.app_id, 'com.zicabella.app');
  eq('extinfo[0] = a2', ev.app_data.extinfo[0], 'a2');
  eq('extinfo[4] = Android version', ev.app_data.extinfo[4], '14');
  eq('madid = AAID', ev.user_data.madid, '38400000-8cf0-11bd-b23e-10b96e40000d');
  check('Android: no idfv', !('idfv' in ev.user_data));
  eq('Android advertiser_tracking_enabled = 1 with AAID', ev.app_data.advertiser_tracking_enabled, 1);
  orders.set('app_and_lat', order('app_and_lat'));
  await delivery.recordSnapAppContext('app_and_lat', { ...androidDevice, madid: undefined }, req);
  await delivery.emitSnapAppPurchase('app_and_lat', PAID);
  ev = lastEvent().body.data[0];
  check('Android limit-ad-tracking → no madid, advertiser_tracking_enabled 0', !('madid' in ev.user_data) && ev.app_data.advertiser_tracking_enabled === 0);
  orders.set('app_and_cod', order('app_and_cod', { paymentStatus: 'cod_upfront_paid' }));
  await delivery.recordSnapAppContext('app_and_cod', androidDevice, req);
  httpCalls.length = 0;
  await delivery.emitSnapAppPurchase('app_and_cod', PAID);
  check('Android COD upfront → one Purchase', httpCalls.length === 1);

  // ── Things that must NOT send ──
  console.log('\n— Must not send');
  httpCalls.length = 0;
  orders.set('app_fail', order('app_fail', { paymentStatus: 'failed' }));
  await delivery.recordSnapAppContext('app_fail', iosDevice, req);
  check('app payment failed → skipped', (await delivery.emitSnapAppPurchase('app_fail', PAID)).status === 'skipped');
  orders.set('app_pending', order('app_pending', { paymentStatus: 'pending' }));
  await delivery.recordSnapAppContext('app_pending', iosDevice, req);
  check('app payment pending → skipped', (await delivery.emitSnapAppPurchase('app_pending', PAID)).status === 'skipped');
  orders.set('app_unconf', order('app_unconf'));
  const unc = await delivery.emitSnapAppPurchase('app_unconf', { paymentConfirmed: false, device: androidDevice, req });
  check('capture not confirmed (authorized / HEADLESS) → skipped', unc.status === 'skipped');
  check('…but device context stored for the captured webhook', rows.get('snap_app|PURCHASE|app_unconf')?.context?.platform === 'android');
  orders.set('app_old_build', order('app_old_build'));
  check('no device context (older app build) → skipped, no web fallback', (await delivery.emitSnapAppPurchase('app_old_build', PAID)).status === 'skipped');
  orders.set('web_order', order('web_order', { orderType: 'REGULAR' }));
  await delivery.recordSnapAppContext('web_order', iosDevice, req);
  check('web order is never sent as an app event', (await delivery.emitSnapAppPurchase('web_order', PAID)).status === 'skipped');
  check('nothing sent in this block', httpCalls.length === 0, httpCalls.length);

  const unconfigured = createSnapAppPurchaseDelivery({ db, send: appCapi.sendSnapAppEvent, env: { SNAP_CAPI_ACCESS_TOKEN: 'x' } as any });
  orders.set('app_noconf', order('app_noconf'));
  await unconfigured.recordSnapAppContext('app_noconf', iosDevice, req);
  const nc = await unconfigured.emitSnapAppPurchase('app_noconf', PAID);
  check('Snap App IDs not configured → skipped, nothing sent', nc.status === 'skipped' && httpCalls.length === 0, nc);

  // ── Device context hygiene ──
  console.log('\n— Device context parsing');
  eq('unknown platform rejected', appCapi.parseSnapDeviceContext({ platform: 'web' }), null);
  check('invalid IDFV dropped', !appCapi.parseSnapDeviceContext({ platform: 'ios', idfv: 'not-a-uuid' })?.idfv);
  check('idfv ignored on Android', !appCapi.parseSnapDeviceContext({ platform: 'android', idfv: iosDevice.idfv })?.idfv);
  check('attStatus ignored on Android', !appCapi.parseSnapDeviceContext({ platform: 'android', attStatus: 'authorized' })?.attStatus);
  check('absurd screen size dropped', appCapi.parseSnapDeviceContext({ platform: 'ios', screenWidth: 1e9 })?.screenWidth === undefined);

  // ── SKU-only legacy item ──
  orders.set('app_sku', order('app_sku', { items: [{ sku: 'ZB-EXOSHELL-32', quantity: 1, price: 1999 }, { variantId: 'gid://shopify/ProductVariant/51813148295449', quantity: 1, price: 1499 }] }));
  await delivery.recordSnapAppContext('app_sku', androidDevice, req);
  await delivery.emitSnapAppPurchase('app_sku', PAID);
  eq('SKU-only item omitted, GID normalized', lastEvent().body.data[0].custom_data.content_ids, ['51813148295449']);

  // ── Static wiring ──
  console.log('\n— Wiring');
  const read = (p: string) => fs.readFileSync(new URL(`../${p}`, import.meta.url), 'utf8');
  const verify = read('app/api/app/payment/verify/route.ts');
  check('verify: MOBILE_APP emit gated on captured status', /paymentCaptured = payment\.status === 'captured' && payment\.captured === true/.test(verify) && /paymentConfirmed: paymentCaptured/.test(verify));
  check('verify: never calls the web sender', !/sendSnapEvent\s*\(|emitSnapPurchase\s*\(/.test(verify));
  check('create-order records device context', /recordSnapAppContext\(pendingOrderId, snapDevice/.test(read('app/api/app/payment/create-order/route.ts')));
  check('webhook sends app purchases on captured/order.paid only', /emitSnapAppPurchase\(order\.id, \{ paymentConfirmed: true \}\)/.test(read('app/api/webhooks/razorpay/route.ts')));
  for (const app of ['ZicaBella', 'ZicaBella-android']) {
    const ui = read(`${app}/src/hooks/useRazorpay.ts`);
    check(`${app}: create-order + verify carry snapDevice`, (ui.match(/getSnapDeviceContext\(\)/g) || []).length === 2);
    check(`${app}: ATT requested after in-app consent`, /onConsentComplete=\{requestTrackingConsentOnce\}/.test(read(`${app}/App.tsx`)));
    check(`${app}: expo-tracking-transparency plugin configured`, /"expo-tracking-transparency"/.test(read(`${app}/app.json`)));
  }

  console.log(`\n${passed} passed, ${failed} failed`);
  if (process.argv[2]) fs.writeFileSync(process.argv[2], report.join('\n'));
  process.exit(failed ? 1 : 0);
}
main().catch(e => { console.error(e); process.exit(1); });
