/**
 * Offline end-to-end verification of Snap Pixel + CAPI tracking.
 *
 *   npx tsx scripts/verify-snap-tracking.ts [report.md]
 *
 * No network: the Snap endpoint, the browser and the database are simulated.
 * What runs for real: identity normalization, the browser hooks, the public
 * /api/snap/event route handler, the CAPI v3 payload builder, and the PURCHASE
 * delivery ledger logic (against an in-memory ledger with the same semantics).
 * Exits non-zero on any failure. Optional arg: write a payload report.
 */
import crypto from 'crypto';
import fs from 'fs';

process.env.SNAP_CAPI_ACCESS_TOKEN = 'test-token';
process.env.NEXT_PUBLIC_SITE_URL = 'https://zicabella.com';
process.env.NEXT_PUBLIC_SNAP_PIXEL_ID = '7d2481be-4ccf-42b2-b9ea-958c6c7bbdcd';

let failed = 0;
let passed = 0;
function check(label: string, ok: boolean, detail?: unknown) {
  if (ok) passed++; else failed++;
  console.log(`${ok ? 'PASS' : 'FAIL'}  ${label}${ok || detail === undefined ? '' : `\n      ${JSON.stringify(detail)}`}`);
}
function eq(label: string, got: unknown, want: unknown) {
  const ok = JSON.stringify(got) === JSON.stringify(want);
  check(label, ok, ok ? undefined : { got, want });
}
const h = (v: string) => crypto.createHash('sha256').update(v).digest('hex');
const DAY = 864e5;
const report: string[] = ['# Snap tracking — verified payloads', '', `Generated by scripts/verify-snap-tracking.ts on ${new Date().toISOString()}`, ''];
const dump = (title: string, obj: unknown) => {
  report.push(`### ${title}`, '```json', JSON.stringify(obj, null, 2), '```', '');
};

// ── Network + browser simulation ────────────────────────────────────────────
type Captured = { url: string; body: any };
const snapCalls: Captured[] = [];      // requests that reached tr.snapchat.com
const relayCalls: Captured[] = [];     // browser → /api/snap/event
const pixelCalls: any[][] = [];        // snaptr(...) calls
let snapResponder: () => { ok: boolean; status: number; json: any } = () => ({ ok: true, status: 200, json: { status: 'VALID' } });

(globalThis as any).fetch = async (url: string, opt: any = {}) => {
  const body = opt.body ? JSON.parse(opt.body) : undefined;
  if (String(url).startsWith('https://tr.snapchat.com/')) {
    snapCalls.push({ url: String(url), body });
    const r = snapResponder();
    return { ok: r.ok, status: r.status, json: async () => r.json };
  }
  if (String(url) === '/api/snap/event') {
    relayCalls.push({ url: String(url), body });
    return { ok: true, status: 200, json: async () => ({ success: true }) };
  }
  return { ok: false, status: 404, json: async () => ({}) };
};

function setBrowser(cookies: Record<string, string>, href = 'https://zicabella.com/products/aerolayer-half-denim') {
  const u = new URL(href);
  (globalThis as any).window = {
    location: { href, hostname: u.hostname, search: u.search, pathname: u.pathname },
    snaptr: (...a: any[]) => pixelCalls.push(a),
  };
  (globalThis as any).document = { cookie: Object.entries(cookies).map(([k, v]) => `${k}=${v}`).join('; ') };
  try {
    Object.defineProperty(globalThis, 'navigator', {
      value: { userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X)' }, configurable: true,
    });
  } catch { /* ignore */ }
}

async function main() {
  const norm = await import('../lib/tracking/identity-normalize');
  const capi = await import('../lib/snap-capi');
  const catalog = await import('../lib/snap/catalog-id');
  const purchase = await import('../lib/snap/purchase');
  const hooks = await import('../hooks/useSnapEvents');
  const route = await import('../app/api/snap/event/route');
  const { NextRequest } = await import('next/server');

  // ══ 1. Identity normalization (worldwide) ══
  console.log('\n— 1. Identity normalization');
  eq('IN phone 10-digit', norm.normalizePhone('98765 43210', 'India'), '919876543210');
  eq('IN phone +91', norm.normalizePhone('+91-98765-43210', 'IN'), '919876543210');
  eq('IN phone trunk 0', norm.normalizePhone('09876543210', 'IN'), '919876543210');
  eq('UAE phone 00971', norm.normalizePhone('00971 50 123 4567', 'AE'), '971501234567');
  eq('UAE phone national 05…', norm.normalizePhone('050 123 4567', 'United Arab Emirates'), '971501234567');
  eq('UK phone national 07…', norm.normalizePhone('07700 900123', 'United Kingdom'), '447700900123');
  eq('UK Snap doc example', norm.normalizePhone('+44 844 412 4653', 'GB'), '448444124653');
  eq('US phone national', norm.normalizePhone('(415) 555-2671', 'US'), '14155552671');
  eq('"+" number beats wrong country', norm.normalizePhone('+14155552671', 'IN'), '14155552671');
  eq('unparseable phone → empty', norm.normalizePhone('12', 'US'), '');
  eq('country United Kingdom → gb', norm.normalizeCountry('United Kingdom'), 'gb');
  eq('country UAE → ae', norm.normalizeCountry('UAE'), 'ae');
  eq('country Germany → de', norm.normalizeCountry('Germany'), 'de');
  eq('country unknown → empty', norm.normalizeCountry('Narnia'), '');
  eq('US state California → ca', norm.normalizeState('California', 'US'), 'ca');
  eq('US ZIP+4 → 5 digits', norm.normalizeZip('94105-1234', 'US'), '94105');
  eq('UK postcode → sector', norm.normalizeZip('SW1A 1AA', 'GB'), 'sw1a1');
  eq('Unicode name kept', norm.normalizeName('Raphaël'), 'raphaël');
  eq('Devanagari name kept', norm.normalizeName('राहुल'), 'राहुल');

  // ══ 2. Meta cookie normalization: no regression for India ══
  console.log('\n— 2. Meta shared-cookie normalization vs main');
  const oldClean = (v: string) => v.trim().toLowerCase().replace(/[^a-z0-9]/g, '');
  const oldPhone = (p: string) => { const d = p.replace(/\D/g, ''); let b = d;
    if (d.length === 12 && d.startsWith('91')) b = d.slice(2); else if (d.length === 11 && d.startsWith('0')) b = d.slice(1);
    return `91${b}`; };
  const oldCountry = (c: string) => { const x = c.trim().toLowerCase();
    if (x === 'india' || x === 'ind' || x === 'in') return 'in';
    if (x === 'united states' || x === 'usa' || x === 'us' || x === 'united states of america') return 'us';
    return x.replace(/[^a-z]/g, '').slice(0, 2); };
  for (const p of ['9876543210', '+91 98765 43210', '919876543210', '09876543210']) eq(`IN phone unchanged: ${p}`, norm.normalizePhone(p, 'India'), oldPhone(p));
  for (const st of ['Uttar Pradesh', 'Maharashtra', 'NCT of Delhi']) eq(`IN state unchanged: ${st}`, norm.normalizeState(st, 'India'), oldClean(st));
  for (const z of ['110001', '201 304']) eq(`IN zip unchanged: ${z}`, norm.normalizeZip(z, 'India'), oldClean(z));
  for (const c of ['India', 'IN']) eq(`country unchanged: ${c}`, norm.normalizeCountry(c), oldCountry(c));

  // ══ 3. Event time — never re-dated ══
  console.log('\n— 3. Event time');
  const now = Date.now();
  check('20-day-old event is NOT sendable', capi.isEventTimeSendable(now - 20 * DAY) === false);
  check('6-day-old event is sendable', capi.isEventTimeSendable(now - 6 * DAY) === true);
  check('1h-in-future event is NOT sendable', capi.isEventTimeSendable(now + 3600e3) === false);
  const fixedMs = now - 2 * DAY;
  eq('event_time is passed through exactly (ms)', capi.buildSnapCapiEvent({
    eventName: 'VIEW_CONTENT', eventId: 'vc_time', eventTime: fixedMs, eventSourceUrl: 'https://zicabella.com/p', userAgent: 'UA',
  }).event_time, fixedMs);
  eq('seconds input converted to ms (same instant)', capi.buildSnapCapiEvent({
    eventName: 'VIEW_CONTENT', eventId: 'vc_time2', eventTime: Math.floor(fixedMs / 1000), eventSourceUrl: 'https://zicabella.com/p', userAgent: 'UA',
  }).event_time, Math.floor(fixedMs / 1000) * 1000);
  snapCalls.length = 0;
  const stale = await capi.sendSnapEvent({
    eventName: 'VIEW_CONTENT', eventId: 'vc_stale', eventTime: now - 20 * DAY, eventSourceUrl: 'https://zicabella.com/p', userAgent: 'UA',
  });
  check('20-day-old event skipped, nothing sent to Snap', stale.skipped === true && snapCalls.length === 0, stale);

  // ══ 4. Catalog ids = feed.xml <g:id> (variant ids) ══
  console.log('\n— 4. Catalog ids');
  // Live https://zicabella.com/feed.xml (first items): g:id 51813148262681 / 51813148295449 / 51813148328217,
  // g:item_group_id 10227656982809 (product id — must never be a content id).
  const FEED_GIDS = ['51813148262681', '51813148295449', '51813148328217'];
  eq('numeric variant id kept', catalog.normalizeVariantId(51813148262681), FEED_GIDS[0]);
  eq('Shopify GID → numeric', catalog.normalizeVariantId('gid://shopify/ProductVariant/51813148295449'), FEED_GIDS[1]);
  eq('"variant:" marker → numeric', catalog.normalizeVariantId('variant:51813148328217'), FEED_GIDS[2]);
  eq('OrderItem.variantId preferred', catalog.snapCatalogIdFromOrderItem({ variantId: FEED_GIDS[0], sku: 'ZB-EXOSHELL-32' }), FEED_GIDS[0]);
  eq('merchandise SKU is never an id', catalog.snapCatalogIdFromOrderItem({ sku: 'ZB-EXOSHELL-32' }), null);
  eq('bare numeric legacy sku not trusted', catalog.snapCatalogIdFromOrderItem({ sku: '10227656982809' }), null);
  eq('app "variant:<id>" sku accepted', catalog.snapCatalogIdFromOrderItem({ sku: `variant:${FEED_GIDS[1]}` }), FEED_GIDS[1]);
  eq('cart payload uses variantId only', hooks.snapCartPayload([
    { variantId: FEED_GIDS[0], productId: '10227656982809', quantity: 2, price: '1499' },
    { variantId: 'gid://shopify/ProductVariant/51813148295449', productId: '10227656982809', quantity: 1, price: '999' },
  ]).ids, [FEED_GIDS[0], FEED_GIDS[1]]);

  // ══ 5. Public relay route hardening ══
  console.log('\n— 5. /api/snap/event hardening');
  const mkReq = (body: unknown, cookie = '', ip = '81.2.69.142') => new NextRequest('https://zicabella.com/api/snap/event', {
    method: 'POST', body: JSON.stringify(body),
    headers: { 'content-type': 'application/json', cookie, 'x-forwarded-for': ip, 'user-agent': 'UA-test' },
  });
  const okBody = {
    eventName: 'VIEW_CONTENT', eventId: 'view_content_snap_abc123', eventTime: Date.now(),
    eventSourceUrl: 'https://zicabella.com/products/aerolayer-half-denim', userAgent: 'UA',
    userData: { country: 'IN' },
    customData: { value: 1499, currency: 'INR', content_ids: [FEED_GIDS[0]] },
  };
  snapCalls.length = 0;
  let r = await route.POST(mkReq({ ...okBody, eventName: 'PURCHASE', customData: { value: 999999, currency: 'INR', order_id: 'x' } }));
  check('PURCHASE refused (400) and nothing sent', r.status === 400 && snapCalls.length === 0, r.status);
  r = await route.POST(mkReq({ ...okBody, eventSourceUrl: 'https://evil.example.com/x' }));
  check('foreign event_source_url host refused', r.status === 400);
  r = await route.POST(mkReq({ ...okBody, customData: { value: 5e9, currency: 'INR' } }));
  check('absurd value refused', r.status === 400);
  r = await route.POST(mkReq({ ...okBody, customData: { contents: [{ id: FEED_GIDS[0], quantity: 1000 }] } }));
  check('absurd quantity refused', r.status === 400);
  r = await route.POST(mkReq({ ...okBody, unexpected: 'field' }));
  check('unknown top-level field refused (strict schema)', r.status === 400);
  r = await route.POST(mkReq({ ...okBody, eventName: 'CUSTOM_EVENT_1' }));
  check('non-allowlisted event refused', r.status === 400);
  snapResponder = () => ({ ok: false, status: 400, json: { status: 'INVALID', reason: 'secret internal detail', access_token: 'leak?' } });
  r = await route.POST(mkReq(okBody, '', '81.2.69.150'));
  const leakText = JSON.stringify(await r.json());
  check('Snap error/token never echoed to the browser', !/secret internal detail|leak|test-token/.test(leakText), leakText);
  snapResponder = () => ({ ok: true, status: 200, json: { status: 'VALID' } });
  snapCalls.length = 0;
  r = await route.POST(mkReq(okBody, '', '81.2.69.151'));
  check('valid VIEW_CONTENT relayed (200, 1 Snap call)', r.status === 200 && snapCalls.length === 1, r.status);
  let limited = 0;
  for (let i = 0; i < 125; i++) {
    const rr = await route.POST(mkReq({ ...okBody, eventId: `view_content_snap_rl${i}x` }, '', '81.2.69.200'));
    if (rr.status === 429) limited++;
  }
  check('per-IP rate limit kicks in after 120/min', limited === 5, { limited });
  let limitedRotating = 0;
  for (let i = 0; i < 125; i++) {
    // Attacker rotates the client-controlled zb_client_ip cookie on every request.
    const rr = await route.POST(mkReq({ ...okBody, eventId: `view_content_snap_rot${i}x` }, `zb_client_ip=203.0.113.${i % 250}`, '81.2.69.201'));
    if (rr.status === 429) limitedRotating++;
  }
  check('rotating zb_client_ip cookie does NOT bypass the limit (keyed on proxy IP)', limitedRotating === 5, { limitedRotating });

  // ══ 6. Web events end-to-end: hook → pixel + relay → route → CAPI v3 ══
  console.log('\n— 6. Web events (pixel + CAPI)');
  report.push('## Web events', '', 'For each event: the browser pixel call, then the final CAPI v3 event that reached Snap.', '');
  const ukGuestCookies = {
    ScCid: 'snap-click-123', _scid: 'scid-cookie-456', zb_external_id: 'zb.ext-789',
    zb_guest_email: h('jane.doe@example.com'), zb_guest_phone: h('447700900123'), zb_guest_country: h('gb'),
  };
  const cookieHeader = Object.entries(ukGuestCookies).map(([k, v]) => `${k}=${v}`).join('; ');
  async function runWebEvent(label: string, fire: () => void, opts: { pixelOnly?: boolean } = {}) {
    pixelCalls.length = 0; relayCalls.length = 0; snapCalls.length = 0;
    fire();
    const track = pixelCalls.find(c => c[0] === 'track');
    const init = [...pixelCalls].reverse().find(c => c[0] === 'init');
    check(`${label}: pixel track fired once`, pixelCalls.filter(c => c[0] === 'track').length === 1);
    let capiEvent: any;
    if (!opts.pixelOnly) {
      check(`${label}: exactly one CAPI relay`, relayCalls.length === 1, relayCalls.length);
      const res = await route.POST(mkReq(relayCalls[0]?.body, cookieHeader, `81.2.69.${10 + (++ipSeq % 200)}`));
      check(`${label}: relay accepted`, res.status === 200, res.status);
      capiEvent = snapCalls[0]?.body?.data?.[0];
      check(`${label}: client_dedup_id === event_id`, track?.[2]?.client_dedup_id === capiEvent?.event_id, { pixel: track?.[2]?.client_dedup_id, capi: capiEvent?.event_id });
      check(`${label}: ScCid + _scid + external_id on CAPI`,
        capiEvent?.user_data?.sc_click_id === 'snap-click-123' && capiEvent?.user_data?.sc_cookie1 === 'scid-cookie-456'
        && Array.isArray(capiEvent?.user_data?.external_id));
    } else {
      check(`${label}: NO browser CAPI relay`, relayCalls.length === 0, relayCalls.length);
    }
    report.push(`### ${label}`, '**Pixel**', '```json', JSON.stringify({ init: init?.[2], track: { event: track?.[1], params: track?.[2] } }, null, 2), '```');
    if (capiEvent) report.push('**CAPI v3 (as sent to Snap)**', '```json', JSON.stringify(capiEvent, null, 2), '```');
    report.push('');
    return { track, capiEvent };
  }
  let ipSeq = 0;
  setBrowser(ukGuestCookies);
  // PAGE_VIEW goes through the route tracker component (React); exercise the same pixel+relay contract here.
  await runWebEvent('PAGE_VIEW', () => {
    const { trackSnapClientEvent } = require('../lib/snapPixel');
    const eventId = 'pv_snap_' + crypto.randomUUID();
    trackSnapClientEvent('PAGE_VIEW', {}, eventId);
    (globalThis as any).fetch('/api/snap/event', { method: 'POST', body: JSON.stringify({
      eventName: 'PAGE_VIEW', eventId, eventTime: Date.now(), eventSourceUrl: (globalThis as any).window.location.href,
      userAgent: 'UA', scClickId: 'snap-click-123', scCookie1: 'scid-cookie-456', externalId: 'zb.ext-789', userData: {},
    }) });
  });
  const vc = await runWebEvent('VIEW_CONTENT', () => hooks.snapTrackViewContent(FEED_GIDS[0], 'AEROLAYER HALF DENIM', 1499, 'INR', 'Denim'));
  eq('VIEW_CONTENT content_ids = feed g:id', vc.capiEvent?.custom_data?.content_ids, [FEED_GIDS[0]]);
  const atc = await runWebEvent('ADD_CART', () => hooks.snapTrackAddToCart(FEED_GIDS[1], 'AEROLAYER HALF DENIM', 1499, 'INR', 'Denim', 2));
  eq('ADD_CART value = unit × qty', atc.capiEvent?.custom_data?.value, 2998);
  eq('ADD_CART num_items', atc.capiEvent?.custom_data?.num_items, '2');
  await runWebEvent('ADD_TO_WISHLIST', () => hooks.snapTrackAddToWishlist(FEED_GIDS[2], 'AEROLAYER HALF DENIM', 'Denim', 1499));
  await runWebEvent('SEARCH', () => hooks.snapTrackSearch('denim jorts'));
  const cart = hooks.snapCartPayload([
    { variantId: FEED_GIDS[0], quantity: 2, price: '1499' }, // denim ×2
    { variantId: FEED_GIDS[2], quantity: 1, price: '799' },  // tee ×1
  ]);
  const sc = await runWebEvent('START_CHECKOUT', () => hooks.snapTrackStartCheckout(3797, cart.numItems, 'INR', 'Denim', cart.ids,
    { em: 'Jane.Doe@Example.com', ph: '07700 900123', fn: 'Jane', ln: 'Doe', ct: 'London', zp: 'SW1A 1AA', country: 'GB' }, cart.contents));
  eq('multi-qty cart num_items = 3', sc.capiEvent?.custom_data?.num_items, '3');
  eq('START_CHECKOUT ph = UK E.164 hash', sc.capiEvent?.user_data?.ph, [h('447700900123')]);
  await runWebEvent('ADD_BILLING', () => hooks.snapTrackAddBilling(3797, 'INR',
    { em: 'jane.doe@example.com', ph: '+44 7700 900123', country: 'GB' }, cart.ids, cart.numItems, cart.contents));
  await runWebEvent('SIGN_UP', () => hooks.snapTrackSignUp({ ph: '+971501234567', fn: 'Aisha' }));
  await runWebEvent('LOGIN', () => hooks.snapTrackLogin({ ph: '+14155552671' }));
  await runWebEvent('SUBSCRIBE', () => hooks.snapTrackSubscribe('new.subscriber@example.com'));
  const pp = await runWebEvent('PURCHASE (browser)', () => hooks.snapTrackPurchase('ord_web_1', 3797, 'INR', cart.ids,
    { em: 'jane.doe@example.com', ph: '07700 900123', country: 'GB' }, 'Denim', cart.contents), { pixelOnly: true });
  eq('pixel PURCHASE client_dedup_id = order id', pp.track?.[2]?.client_dedup_id, 'ord_web_1');
  eq('pixel PURCHASE transaction_id = order id', pp.track?.[2]?.transaction_id, 'ord_web_1');
  eq('pixel PURCHASE number_items = 3', pp.track?.[2]?.number_items, 3);

  // ══ 6b. ADD_CART value/currency on Wishlist / Bookmark drawer / Complete Collection ══
  console.log('\n— 6b. ADD_CART currency/value (new entry points, international shopper)');
  const gp = await import('../lib/global-pricing-client');
  const usConfig: any = { code: 'US', currencyCode: 'USD', currencySymbol: '$', locale: 'en-US', multiplier: 1.25, exchangeRate: 0.012, isBase: false };
  const variantINR = { id: 51813148262681, price: '1499.00' };
  const usDisplay = gp.formatPriceWithConfig(parseFloat(variantINR.price), usConfig, true);
  // Exactly what the three components call (copied from their source, asserted below):
  setBrowser({}, 'https://zicabella.com/wishlist');
  pixelCalls.length = 0; relayCalls.length = 0;
  hooks.snapTrackAddToCart(variantINR.id.toString(), 'AEROLAYER HALF DENIM', parseFloat(variantINR.price || '0'), 'INR', 'Denim');
  const atcPixel = pixelCalls.find(c => c[0] === 'track')?.[2];
  const atcCapi = relayCalls[0]?.body?.customData;
  eq('ADD_CART value = Shopify variant price (INR base), currency INR', [atcPixel?.price, atcPixel?.currency, atcCapi?.value, atcCapi?.currency], [1499, 'INR', 1499, 'INR']);
  check('US display price (USD, incl. multiplier) is NOT used as the event value', usDisplay.currencyCode === 'USD' && atcCapi?.value !== usDisplay.amount, { display: usDisplay });
  const cartLine = hooks.snapCartPayload([{ variantId: String(variantINR.id), quantity: 1, price: variantINR.price }]);
  eq('same value as the cart line → START_CHECKOUT / ADD_BILLING (INR base)', cartLine.contents[0].item_price, atcCapi?.value);
  const pdpPattern = /trackSnapAddToCart\(variant\.id\.toString\(\), product\.title, parseFloat\(variant\.price \|\| "0"\), 'INR', product\.product_type\)/;
  check('PDP uses the same (variant.price, INR) pattern', pdpPattern.test(fs.readFileSync(new URL('../app/products/[id]/ProductDetailsClient.tsx', import.meta.url), 'utf8')));
  for (const f of ['app/wishlist/page.tsx', 'components/BookmarkDrawer.tsx', 'components/CompleteCollectionButton.tsx']) {
    const src = fs.readFileSync(new URL(`../${f}`, import.meta.url), 'utf8');
    const calls = src.match(/snapTrackAddToCart\([^;]*\);/g) || [];
    check(`${f}: every Snap ADD_CART passes variant.price with 'INR' (no display/converted price)`,
      calls.length > 0 && calls.every(c => /parseFloat\(variant\.price \|\| "0"\), 'INR'/.test(c) && !/fmtPrice|formatPrice|useCountryPrice/.test(c)), calls);
    check(`${f}: cart line gets the same variant.price`, /price: variant\.price/.test(src));
  }

  // ══ 7. Authoritative server PURCHASE + idempotency ══
  console.log('\n— 7. Server PURCHASE ledger');
  report.push('## Server PURCHASE (lib/snap/purchase.ts)', '');
  const orders = new Map<string, any>();
  const rows = new Map<string, any>();
  const keyOf = (w: any) => { const k = w.platform_eventName_orderId; return `${k.platform}|${k.eventName}|${k.orderId}`; };
  let idSeq = 0;
  const matchWhere = (row: any, w: any): boolean => {
    if (w.id && row.id !== w.id) return false;
    if (w.platform && row.platform !== w.platform) return false;
    if (w.eventName && row.eventName !== w.eventName) return false;
    if (w.attempts?.lt !== undefined && !(row.attempts < w.attempts.lt)) return false;
    if (w.status !== undefined) {
      if (typeof w.status === 'string' && row.status !== w.status) return false;
      if (w.status?.in && !w.status.in.includes(row.status)) return false;
    }
    if (w.leaseUntil?.lt && !(row.leaseUntil && row.leaseUntil < w.leaseUntil.lt)) return false;
    if (w.createdAt?.lt && !(row.createdAt < w.createdAt.lt)) return false;
    if (w.createdAt?.gt && !(row.createdAt > w.createdAt.gt)) return false;
    if (w.OR && !w.OR.some((o: any) => matchWhere(row, o))) return false;
    return true;
  };
  const tick = () => new Promise(res => setImmediate(res));
  const fakeDb = {
    order: { findUnique: async ({ where }: any) => { await tick(); return orders.get(where.id) || null; } },
    adConversionDelivery: {
      findUnique: async ({ where }: any) => { await tick(); const r0 = rows.get(keyOf(where)); return r0 ? { ...r0 } : null; },
      create: async ({ data }: any) => {
        await tick();
        const k = `${data.platform}|${data.eventName}|${data.orderId}`;
        if (rows.has(k)) { const e: any = new Error('Unique constraint'); e.code = 'P2002'; throw e; }
        const row = { id: `row${++idSeq}`, status: 'pending', attempts: 0, leaseUntil: null, eventTime: null, sentAt: null, lastError: null, createdAt: new Date(), updatedAt: new Date(), ...data };
        rows.set(k, row); return { ...row };
      },
      update: async ({ where, data }: any) => {
        await tick(); const row = rows.get(keyOf(where)); if (!row) throw new Error('not found');
        Object.assign(row, data, { updatedAt: new Date() }); return { ...row };
      },
      // Atomic, like a single SQL UPDATE … WHERE (no await between test and set).
      updateMany: async ({ where, data }: any) => {
        await tick(); let count = 0;
        for (const row of rows.values()) {
          if (!matchWhere(row, where)) continue;
          for (const [k, v] of Object.entries<any>(data)) row[k] = v && typeof v === 'object' && 'increment' in v ? row[k] + v.increment : v;
          row.updatedAt = new Date(); count++;
        }
        return { count };
      },
      findMany: async ({ where, take }: any) => { await tick(); return [...rows.values()].filter(r0 => matchWhere(r0, where)).sort((a, b) => a.createdAt - b.createdAt).slice(0, take); },
    },
  };
  const sent: any[] = [];
  let sendMode: 'ok' | 'fail' = 'ok';
  const fakeSend = async (p: any) => { await tick(); sent.push(p); return sendMode === 'ok' ? { success: true } : { success: false, error: 'HTTP 500' }; };
  const delivery = purchase.createSnapPurchaseDelivery({ db: fakeDb, send: fakeSend });

  const baseOrder = (id: string, over: any = {}) => ({
    id, orderType: 'REGULAR', paymentStatus: 'paid', totalPrice: 3797, currency: 'INR', customerId: 'cust_1',
    createdAt: new Date(Date.now() - 60e3), paymentCapturedAt: new Date(Date.now() - 30e3),
    customer: { email: 'Jane.Doe@Example.com', phone: '+44 7700 900123', name: 'Jane Doe' },
    shippingAddress: JSON.stringify({ city: 'London', state: 'Greater London', zip: 'SW1A 1AA', country: 'United Kingdom', countryCode: 'GB' }),
    items: [
      { variantId: FEED_GIDS[0], sku: FEED_GIDS[0], quantity: 2, price: 1499 },
      { variantId: FEED_GIDS[2], sku: FEED_GIDS[2], quantity: 1, price: 799 },
    ],
    ...over,
  });
  const PAID = { paymentConfirmed: true };
  const scClick = { scClickId: 'snap-click-123', scCookie1: 'scid-cookie-456', externalId: 'zb.ext-789', ipAddress: '81.2.69.142', userAgent: 'UA' };

  // Scenario: Snap-ad visitor, prepaid, concurrent paths (checkout/complete + webhook ×4)
  orders.set('ord_prepaid', baseOrder('ord_prepaid'));
  await delivery.recordSnapPurchaseContext('ord_prepaid', scClick); // Razorpay pre-create
  const results = await Promise.all([
    delivery.emitSnapPurchase('ord_prepaid', scClick, PAID), delivery.emitSnapPurchase('ord_prepaid', undefined, PAID),
    delivery.emitSnapPurchase('ord_prepaid', undefined, PAID), delivery.emitSnapPurchase('ord_prepaid', undefined, PAID), delivery.emitSnapPurchase('ord_prepaid', undefined, PAID),
  ]);
  check('5 concurrent emits → exactly ONE send', sent.length === 1, { sends: sent.length, results });
  const row = rows.get('snap|PURCHASE|ord_prepaid');
  check('ledger row sent with sentAt', row.status === 'sent' && row.sentAt instanceof Date, row);
  await delivery.emitSnapPurchase('ord_prepaid', scClick, PAID);
  check('later emit after success → no resend', sent.length === 1);
  const ev = capi.buildSnapCapiEvent(sent[0]);
  dump('PURCHASE — Snap-ad visitor, prepaid Razorpay (CAPI v3 as sent)', ev);
  eq('event_id = order id', ev.event_id, 'ord_prepaid');
  eq('order_id = order id', ev.custom_data.order_id, 'ord_prepaid');
  eq('action_source WEB', ev.action_source, 'WEB');
  eq('value from DB', ev.custom_data.value, 3797);
  eq('currency from DB', ev.custom_data.currency, 'INR');
  eq('content_ids = feed g:id variant ids', ev.custom_data.content_ids, [FEED_GIDS[0], FEED_GIDS[2]]);
  eq('num_items = 3 (denim×2 + tee×1)', ev.custom_data.num_items, '3');
  eq('sc_click_id from recorded context', ev.user_data.sc_click_id, 'snap-click-123');
  eq('sc_cookie1 from recorded context', ev.user_data.sc_cookie1, 'scid-cookie-456');
  eq('external_id hashed', ev.user_data.external_id, [h('zb.ext-789')]);
  eq('ph hashed UK E.164', ev.user_data.ph, [h('447700900123')]);
  eq('country hashed gb', ev.user_data.country, [h('gb')]);
  const pixelForSameOrder = pp.track?.[2];
  check('dedup pair matches pixel (client_dedup_id/transaction_id ↔ event_id/order_id)',
    pixelForSameOrder?.client_dedup_id === 'ord_web_1' && pixelForSameOrder?.transaction_id === 'ord_web_1');

  // Scenario: webhook-only completion (browser never returned) still has click ids
  sent.length = 0;
  orders.set('ord_webhook', baseOrder('ord_webhook'));
  await delivery.recordSnapPurchaseContext('ord_webhook', scClick);
  await delivery.emitSnapPurchase('ord_webhook', undefined, PAID); // webhook: no request context
  eq('webhook-only purchase keeps ScCid from pre-create', capi.buildSnapCapiEvent(sent[0]).user_data.sc_click_id, 'snap-click-123');

  // Scenario: direct visitor (no Snap click)
  sent.length = 0;
  orders.set('ord_direct', baseOrder('ord_direct'));
  await delivery.emitSnapPurchase('ord_direct', { ipAddress: '81.2.69.142', userAgent: 'UA' }, PAID);
  const evDirect = capi.buildSnapCapiEvent(sent[0]);
  check('direct visitor: no sc_click_id, PII still present', !evDirect.user_data.sc_click_id && !!evDirect.user_data.em);
  dump('PURCHASE — direct visitor (no ScCid)', evDirect);

  // Scenario: COD order with Razorpay upfront → counts
  sent.length = 0;
  orders.set('ord_cod', baseOrder('ord_cod', { paymentStatus: 'cod_upfront_paid', totalPrice: 2499 }));
  await delivery.emitSnapPurchase('ord_cod', scClick, PAID);
  check('COD (cod_upfront_paid) sends once with full order value', sent.length === 1 && capi.buildSnapCapiEvent(sent[0]).custom_data.value === 2499);

  // Scenario: capture not confirmed (e.g. checkout/complete could not verify capture,
  // or only payment.authorized) → nothing sent, click context kept for the confirming path
  sent.length = 0;
  orders.set('ord_unconfirmed', baseOrder('ord_unconfirmed'));
  const unconf = await delivery.emitSnapPurchase('ord_unconfirmed', scClick, { paymentConfirmed: false });
  check('capture not confirmed → nothing sent', unconf.status === 'skipped' && sent.length === 0, unconf);
  eq('…but ScCid kept for the webhook', (rows.get('snap|PURCHASE|ord_unconfirmed')?.context as any)?.scClickId, 'snap-click-123');
  await delivery.emitSnapPurchase('ord_unconfirmed', undefined, PAID); // later payment.captured webhook
  check('captured webhook later → sent once with stored ScCid', sent.length === 1 && capi.buildSnapCapiEvent(sent[0]).user_data.sc_click_id === 'snap-click-123');

  // Scenario: failed / pending / underpaid payment → never sends
  sent.length = 0;
  for (const st of ['payment_pending', 'failed', 'partially_paid', '']) {
    orders.set(`ord_${st || 'empty'}`, baseOrder(`ord_${st || 'empty'}`, { paymentStatus: st }));
    const out = await delivery.emitSnapPurchase(`ord_${st || 'empty'}`, scClick, PAID);
    check(`paymentStatus "${st}" → no Purchase`, out.status === 'skipped');
  }
  check('nothing sent for unpaid orders', sent.length === 0);

  // Scenario: native app orders are never sent through the web pixel
  for (const t of ['MOBILE_APP', 'MOBILE', 'APP']) {
    orders.set(`ord_${t}`, baseOrder(`ord_${t}`, { orderType: t }));
    const out = await delivery.emitSnapPurchase(`ord_${t}`, scClick, PAID);
    check(`orderType ${t} → not sent as WEB`, out.status === 'skipped');
  }
  check('no app purchase sent', sent.length === 0);

  // Scenario: app-style SKU without variantId → item omitted, never a fake id
  sent.length = 0;
  orders.set('ord_sku', baseOrder('ord_sku', { items: [
    { sku: 'ZB-EXOSHELL-32', quantity: 1, price: 1999 },
    { variantId: FEED_GIDS[1], sku: 'ZB-AERO-S', quantity: 1, price: 1499 },
  ], totalPrice: 3498 }));
  await delivery.emitSnapPurchase('ord_sku', scClick, PAID);
  eq('SKU-only item left out of content_ids', capi.buildSnapCapiEvent(sent[0]).custom_data.content_ids, [FEED_GIDS[1]]);
  eq('…but still counted in num_items', capi.buildSnapCapiEvent(sent[0]).custom_data.num_items, '2');

  // Scenario: Snap failure → failed (no sentAt) → retry keeps the same event_id and conversion time
  sent.length = 0; sendMode = 'fail';
  orders.set('ord_retry', baseOrder('ord_retry'));
  const first = await delivery.emitSnapPurchase('ord_retry', scClick, PAID);
  const failedRow = { ...rows.get('snap|PURCHASE|ord_retry') };
  check('failed send → status failed, sentAt null', first.status === 'failed' && failedRow.status === 'failed' && failedRow.sentAt === null, failedRow);
  sendMode = 'ok';
  const tally = await delivery.retryPendingSnapPurchases(10);
  check('retry job resends failed row', tally.retry_sent === 1, tally);
  check('retry uses same event_id', sent[0].eventId === sent[1].eventId && sent[1].eventId === 'ord_retry');
  check('retry uses same event_time', sent[0].eventTime === sent[1].eventTime);
  check('sentAt set only after success', rows.get('snap|PURCHASE|ord_retry').status === 'sent' && rows.get('snap|PURCHASE|ord_retry').sentAt instanceof Date);

  // Scenario: stale lease (crashed sender) is reclaimable, live lease is not
  sent.length = 0;
  orders.set('ord_lease', baseOrder('ord_lease'));
  await fakeDb.adConversionDelivery.create({ data: { platform: 'snap', eventName: 'PURCHASE', orderId: 'ord_lease', eventId: 'ord_lease', status: 'sending', leaseUntil: new Date(Date.now() + 30e3), attempts: 1 } });
  await delivery.emitSnapPurchase('ord_lease', scClick, PAID);
  check('live lease held by another process → no send', sent.length === 0);
  rows.get('snap|PURCHASE|ord_lease').leaseUntil = new Date(Date.now() - 1000);
  await delivery.emitSnapPurchase('ord_lease', scClick, PAID);
  check('expired lease → reclaimed and sent once', sent.length === 1);

  // Scenario: 20-day-old order → skipped, never re-dated
  sent.length = 0;
  orders.set('ord_old', baseOrder('ord_old', { paymentCapturedAt: new Date(Date.now() - 20 * DAY), createdAt: new Date(Date.now() - 20 * DAY) }));
  const old = await delivery.emitSnapPurchase('ord_old', scClick, PAID);
  check('20-day-old purchase skipped, nothing sent', old.status === 'skipped' && sent.length === 0, old);
  eq('…and marked non-sendable in the ledger', rows.get('snap|PURCHASE|ord_old').status, 'skipped');

  // Scenario: India / UAE / US customers
  for (const [label, phone, country, want] of [
    ['India', '9876543210', 'India', '919876543210'],
    ['UAE', '050 123 4567', 'AE', '971501234567'],
    ['US', '(415) 555-2671', 'US', '14155552671'],
  ] as const) {
    sent.length = 0;
    const oid = `ord_${label}`;
    orders.set(oid, baseOrder(oid, { customer: { email: 'x@example.com', phone, name: 'A B' },
      shippingAddress: JSON.stringify({ country, city: 'X' }) }));
    await delivery.emitSnapPurchase(oid, scClick, PAID);
    eq(`${label} customer phone hash`, capi.buildSnapCapiEvent(sent[0]).user_data.ph, [h(want)]);
  }

  // ══ 7b. Stranded PENDING rows: recovered only after DB paid + verified capture ══
  console.log('\n— 7b. Pending-row recovery');
  const captured = new Set<string>();
  const verifyCapture = async (o: any) => captured.has(o.id);
  const recovering = purchase.createSnapPurchaseDelivery({ db: fakeDb, send: fakeSend, verifyCapture });
  const ageRow = (orderId: string, ms: number) => { const r0 = rows.get(`snap|PURCHASE|${orderId}`); r0.createdAt = new Date(Date.now() - ms); };
  const MIN = 60e3;
  sent.length = 0;
  // a) checkout could not confirm capture, captured webhook never arrived
  orders.set('ord_stranded', baseOrder('ord_stranded', { razorpayPaymentId: 'pay_strand' }));
  await recovering.emitSnapPurchase('ord_stranded', scClick, { paymentConfirmed: false });
  ageRow('ord_stranded', 20 * MIN);
  let tallyR = await recovering.retryPendingSnapPurchases(25);
  check('paid in DB but capture NOT verified → stays pending, nothing sent', sent.length === 0 && rows.get('snap|PURCHASE|ord_stranded').status === 'pending', tallyR);
  captured.add('ord_stranded');
  tallyR = await recovering.retryPendingSnapPurchases(25);
  check('capture verified → recovered and sent once', sent.length === 1 && tallyR.recovered_sent === 1, tallyR);
  eq('recovered event keeps the original ScCid', capi.buildSnapCapiEvent(sent[0]).user_data.sc_click_id, 'snap-click-123');
  await recovering.retryPendingSnapPurchases(25);
  check('second retry run → no resend', sent.length === 1);
  // b) unpaid order with a pending row → never sent
  orders.set('ord_abandoned', baseOrder('ord_abandoned', { paymentStatus: 'payment_pending' }));
  await recovering.recordSnapPurchaseContext('ord_abandoned', scClick);
  ageRow('ord_abandoned', 30 * MIN); captured.add('ord_abandoned');
  tallyR = await recovering.retryPendingSnapPurchases(25);
  check('pending row for unpaid order → not sent', sent.length === 1 && rows.get('snap|PURCHASE|ord_abandoned').status === 'pending', tallyR);
  // c) too fresh → left to the live paths
  orders.set('ord_fresh', baseOrder('ord_fresh'));
  await recovering.recordSnapPurchaseContext('ord_fresh', scClick); captured.add('ord_fresh');
  ageRow('ord_fresh', 5 * MIN);
  await recovering.retryPendingSnapPurchases(25);
  check('pending row younger than 15 min → untouched', rows.get('snap|PURCHASE|ord_fresh').status === 'pending' && sent.length === 1);
  // d) older than Snap window → expired, never sent
  orders.set('ord_ancient', baseOrder('ord_ancient'));
  await recovering.recordSnapPurchaseContext('ord_ancient', scClick); captured.add('ord_ancient');
  ageRow('ord_ancient', 8 * DAY);
  tallyR = await recovering.retryPendingSnapPurchases(25);
  check('pending row older than 7 days → expired (skipped), not sent', rows.get('snap|PURCHASE|ord_ancient').status === 'skipped' && sent.length === 1, tallyR);
  // e) native app order row on the web platform → never sent as WEB
  orders.set('ord_app_pending', baseOrder('ord_app_pending', { orderType: 'MOBILE_APP' }));
  await recovering.recordSnapPurchaseContext('ord_app_pending', scClick); captured.add('ord_app_pending');
  ageRow('ord_app_pending', 30 * MIN);
  await recovering.retryPendingSnapPurchases(25);
  check('app order pending row → not sent as WEB', sent.length === 1);
  // f) without a capture verifier, pending rows are never recovered
  orders.set('ord_noverifier', baseOrder('ord_noverifier'));
  await delivery.recordSnapPurchaseContext('ord_noverifier', scClick);
  ageRow('ord_noverifier', 30 * MIN);
  await delivery.retryPendingSnapPurchases(25);
  check('no capture verifier configured → pending never recovered', rows.get('snap|PURCHASE|ord_noverifier').status === 'pending' && sent.length === 1);

  // Production capture proof (lib/razorpay-payment.ts fetchCapturedPayment) semantics
  const { fetchCapturedPayment } = await import('../lib/razorpay-payment');
  const fakeRzp = (p: any) => (async () => ({ ok: true, json: async () => p })) as any;
  const creds = { key_id: 'k', key_secret: 's' };
  check('Razorpay captured → proof accepted', await fetchCapturedPayment('pay_A1', creds, fakeRzp({ id: 'pay_A1', status: 'captured', captured: true, amount_refunded: 0 })).then(() => true, () => false));
  check('Razorpay authorized → proof rejected', await fetchCapturedPayment('pay_A2', creds, fakeRzp({ id: 'pay_A2', status: 'authorized', captured: false })).then(() => false, () => true));
  check('Razorpay refunded → proof rejected', await fetchCapturedPayment('pay_A3', creds, fakeRzp({ id: 'pay_A3', status: 'captured', captured: true, amount_refunded: 100 })).then(() => false, () => true));

  // ══ 8. Static guarantees in route files ══
  console.log('\n— 8. Static checks');
  const read = (p: string) => fs.readFileSync(new URL(`../${p}`, import.meta.url), 'utf8');
  check('app payment verify no longer calls sendSnapEvent', !/sendSnapEvent\s*\(/.test(read('app/api/app/payment/verify/route.ts')));
  check('checkout/complete has no inline sendSnapEvent', !/sendSnapEvent\s*\(/.test(read('app/api/checkout/complete/route.ts')));
  check('confirmation page gates Snap purchase on payment status', /snapPayStatus === "paid"/.test(read('app/orders/[id]/confirmation/page.tsx')));
  for (const f of ['app/wishlist/page.tsx', 'components/BookmarkDrawer.tsx', 'components/CompleteCollectionButton.tsx']) {
    const src = read(f);
    const adds = (src.match(/\baddToCart\(\{/g) || []).length;
    const tracks = (src.match(/snapTrackAddToCart\(/g) || []).length;
    check(`${f}: one Snap ADD_CART per direct add (${adds} adds)`, adds > 0 && adds === tracks, { adds, tracks });
  }
  const wh = read('app/api/webhooks/razorpay/route.ts');
  check('webhook: payment.authorized is not in the paid path',
    !/eventType === 'payment\.captured' \|\| eventType === 'order\.paid' \|\| eventType === 'payment\.authorized'/.test(wh)
    && /if \(eventType === 'payment\.authorized'\) \{[\s\S]*?return NextResponse\.json/.test(wh));
  const co = read('app/api/app/payment/create-order/route.ts');
  check('app create-order persists variantId on pending OrderItem + MobileOrderItem',
    (co.match(/variantId: item\.variantId/g) || []).length === 2 && /normalizeVariantId\(li\.variantId \|\| li\.variant_id\)/.test(co));
  check('footer fires SUBSCRIBE only after confirmed save',
    /if \(!res\.ok \|\| !data\?\.ok\)[\s\S]*?return;[\s\S]*?trackSnapSubscribe/.test(read('components/StorefrontFooterClient.tsx')));

  console.log(`\n${passed} passed, ${failed} failed`);
  const out = process.argv[2];
  if (out) { fs.writeFileSync(out, report.join('\n')); console.log(`report → ${out}`); }
  process.exit(failed ? 1 : 0);
}

main().catch(err => { console.error(err); process.exit(1); });
